[package]
name = "rust-webapi-template"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0", features = ["full"] }
tower = "0"
rand = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.29"
